sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t gsg2820/rpi-dyndns:build .
# test image
- docker run --entrypoint /bin/ash gsg2820/rpi-dyndns:build -c "cat /etc/ddclient/ddclient.conf"
after_success:
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "FROM " Dockerfile | sed 's/.*://')
    docker tag gsg2820/rpi-dyndns:build gsg2820/rpi-dyndns:$TAG
    docker tag gsg2820/rpi-dyndns:build gsg2820/rpi-dyndns:latest
    docker push gsg2820/rpi-dyndns:$TAG
    docker push gsg2820/rpi-dyndns:latest
  fi
